title: Creeva's World 3.0
baseurl: /testsite
description: Creeva's personal site
exclude:
- LICENSE
- README.adoc
- Gemfile
- Gemfile.lock
- Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - icons=font
    - idseparator=_
    - stylesdir=css
    - source-highlighter=coderay
    - liquid
paginate: 10
paginate_path: "/page:num/"
plugins:
  - jekyll-asciidoc
  - jekyll-paginate
