
---
layout: default
title: Clark Carmean
---

== Clark Carmean

https://www.lvc.edu/programs/music/carmean-music-series/

https://www.lvc.edu/give/funding-opportunities/faculty-endowed-funds/fine-arts/


https://www.hmdb.org/m.asp?m=246800

https://www.amazon.com/Quittapahilla-Classic-Reprint-Lebanon-College/dp/0428654207

=== Obituary

https://obits.pennlive.com/us/obituaries/pennlive/name/d-carmean-obituary?id=15483340

Dr. D. Clark Carmean H'85, who with his late wife, Edna, enthusiastically dedicated himself to generations of Lebanon Valley College students and was deeply loved in return, died peacefully in his sleep September 14, 2005 at United Christian Church Home in North Annville.

The dean of admission emeritus and former music professor was 101. He was highly regarded on campus for his generosity, wisdom, and kindness.

Carmean was born May 22, 1904 in Marysville, Ohio, the son of Donald and Hattie Carmean. His long association with the College began in 1933 when he became an instructor of music education and string instruments. He went on to serve as dean of men from 1935 to 1940 and as director of admissions from 1949 to 1973. Carmean, an Ohio Wesleyan graduate, received his master's degree in music education in 1932 from Columbia Teachers College in New York City.

Long after he retired from the College in 1972, Carmean was still sought after for his advice. Gregory Stanson, LVC's vice president for enrollment and student affairs, and a member of the class of 1963, called Carmean his mentor. "He was a very wise person. Clark personified all the values I grew up with at home. He was a great role model for generations of students."

"The College was really his life," said Robert E. Harnish, manager of the LVC bookstore. Harnish remembers that, even after they retired, Carmean and his wife, Edna, who died in 2001, would volunteer in the College's admission office, handwriting little notes to encourage students to come to LVC.

To provide for the College community they were devoted to, the couple, who had no children of their own, became members of the College's Laureate Society, which includes those who have given in excess of $1 million to the College. The Carmeans also donated Cuewe-Pehelle, the larger-than-life bronze statue of an Algonquin Indian woman in front of Garber Science Center. New York sculptor Audrey Flack created the statue with outstretched arms to represent the welcoming spirit of the Lebanon Valley. The plaza that surrounds the sculpture was named in the couple's honor.

As honorary co-chairs of Lebanon Valley College's TOWARD 2001 campaign, the Carmeans assisted in a major fundraising venture which exceeded its goal to raise over $23.9 million. In 1977, the couples' love of music led to their endowing the Carmean Distinguished Chair in Music and in 1982 established the Carmean String Ensemble Scholarship.

Carmean served 12 years on the Annville school board in the 1950's and 1960's, and oversaw the building of Annville-Cleona High School. He also taught Sunday school at Annville United Methodist Church and, along with his wife, volunteered at Good Samaritan Hospital in Lebanon. Carmean received an honorary doctorate of humane letters from the College in 1985.

His wife was a long-time staff assistant in various departments, including music, admissions, public relations, and the president's office. She also served as a writer/editor for Alumni Review, as executive secretary for the College's Centennial celebration, and was the College historian.

Memorial Services will be scheduled and announced at a later date. Kreamer Funeral Home, Annville is handling arrangements.

In lieu of flowers, contributions may be made to the Dr. Clark and Dr. Edna Carmean Scholarship Fund, c/o Advancement Office of Lebanon Valley College, 101 N. College Avenue, Annville, PA 17003.