= Grand Army of the Republic Band
:page-layout: page

Rewrite

*ACKLEY: THE MUSIC MAN:* The Grand Army of the Republic (aka. G.A.R.) was a fraternal organization composed of veterans of the Union Army, Union Navy, Marines and the U.S. Revenue Cutter Service who served in the American Civil War. It was founded in 1866 in Springfield, Illinois, and grew to include hundreds of “posts” across the nation. It was comparable to present-day veterans organizations such as the American Legion, Veterans of Foreign Wars and AmVets. It dissolved in 1956 upon the death of its last member Albert Woolson of Duluth, Minnesota. But back in the early years of the 20th century it was still a very strong and active organization all across our nation.

In Vermilion the G.A.R. Chapter was known as the Delker Post. It was named in honor of Captain Henry Delker. Delker was born in Baden, Germany on the 4th day of July in 1836. He passed from life (as near as I can tell) at exactly 4:00 p.m. on Monday, December 22, 1890 in Vermilion, Ohio. He was, oddly enough, a belated casualty of the American Civil War. Wounded in the Battle of Nashville in December of 1864 the bullet he received on that battlefield 26 years earlier had finally proven fatal. But that is another story.

In the early years of the 20th century the Delker Post of the G.A.R. organized the band seen posing for the accompanying portrait. It was taken in Exchange Park about 1911. In September of that same year Vermilion hosted a big band convention inviting bands from all over the region to attend. Although some of the band members pictured may have been veterans from the War of the Rebellion, most were actually relatives of veterans (like my grandfather) or just local musicians who were talented and enjoyed being part of the company.

Pictured in the *Top Row:* John Krapp, Alfred Buell, Clarence Walper, Pearl Roscoe, Jake Baumhart, John Becker, Miles Lawless, Otto Kuehlman, George Becker, Phil Darley, and Charles Horton. *Middle Row:* Tony Becker, Carl Blair, Ralph Risden, Charles Krapp, T.J. Ball, Ed Law, Fred Morgan, Creight Powell and John Malik. *Bottom Row:* P.B. Morgan, August Schwensen, Will Krapp, Earl Childs, Fred Krapp, Walter Murschell, Henry Reis, Cliff Squires and E.B. Ackley the band director. Ackley is also pictured in the middle inset.

Band Director Ackley was truly an interesting personality. He was born Eugene Baker Ackley on the first day of November in 1871 in Illinois and died in Sandusky on the first day of September in 1957 at the tender age of 85 years. He was, of course, a consummate musician. But he was also a talented businessman. In fact, when he died, he was board chairman of the Western Security Bank in Sandusky.

He began his musical career while a youngster as a trouper with the traveling Gorman Minstrel Show and with that show played in every state in the union during the 1880s. In the late 1880s a member of The Great Western Band, then performing at Cedar Point, noting the unusual musical ability of one member of the Gorman troupe (namely Ackley), got in touch with him and brought him to Sandusky to join Western group.

The Great Western Band had been founded in 1867 by a man named Charles Baetz, one of the early (1888) general managers of the Cedar Point Pleasure Resort Company. The Western Band played for both daily concerts and dances at the resort. Shortly after he began performing with the band it “disbanded” [sic] and he formed his own band and with it continued to perform at Cedar Point.

However, his band was but one of many he organized and directed over ensuing years. Vermilion’s award winning G.A.R. Band was but one of them. In addition to it he directed the Zenobia Shrine band in Toledo. And in Sandusky he organized an orchestra that played for numerous formal events in the region. He frequently acted as a guest director of a large Sandusky High School orchestra and organized a large and valuable library of music for the school. In his spare time, he operated (of all things) a pool and billiard parlor and was also engaged in the wholesale tobacco business. He was also an active member of local Masonic lodge becoming a Master Mason; a member of the Shriners in Toledo; the Sandusky Elks, Eagles, Odd Fellows and director of the Erie County Ohio Automobile Club.

When he passed away, he was serving as the chairman of the Good Samaritan Hospital building fund and, as previously indicated, board chairman of the Western Security Bank. So, to be sure Band Director Ackley, the music man passed, but the harmonies he put together during his lifetime certainly did not. He had simply passed the baton.