= Alma Mater
:page-layout: page

=== Alma Mater

.1986 Vermilion Sailor Alumni Band - Alma Mater
video::FVjpZ7h4xlE[youtube, width=640, height=360, align=center]

.1987 Vermilion Sailor Alumni Band - Alma Mater
video::Ns5p6o3jQ6s[youtube, width=640, height=360, align=center]

.1988 Vermilion Sailor Alumni Band - Alma Mater
video::cZCK0qq7XeE[youtube, width=640, height=360, align=center]

.1989 Vermilion Sailor Alumni Band - Alma Mater
video::d5Dh6M9sUnE[youtube, width=640, height=360, align=center]

.1990 Vermilion Sailor Alumni Band - Alma Mater
video::cmqT3WR7lVQ[youtube, width=640, height=360, align=center]

.1991 Vermilion Sailor Alumni Band - Alma Mater
video::e_FEjoTwObk[youtube, width=640, height=360, align=center]

.1992 Vermilion Sailor Alumni Band - Alma Mater
video::wsmjfHiq3Bs[youtube, width=640, height=360, align=center]

.1993 Vermilion Sailor Alumni Band - Alma Mater
video::wknY6ymgubY[youtube, width=640, height=360, align=center]

.1994 Vermilion Sailor Alumni Band - Alma Mater
video::8q7_-RY_CJ8[youtube, width=640, height=360, align=center]

.1991-1992 Vermilion Sailor Marching Band - Alma Mater - First Home Game
video::c7cl-exSjVQ[youtube, width=640, height=360, align=center]

.1991-1992 Vermilion Sailor Marching Band - Alma Mater - Homecoming Ceremony
video::q_Ton4xVoGA[youtube, width=640, height=360, align=center]

.1993-1994 Vermilion Sailor Marching Band - Alma Mater - Fight Song Across The Field
video::zH_HNE29i4A[youtube, width=640, height=360, align=center]

.1995-1996 Vermilion Sailor Marching Band - Alma Mater - Band In Review
video::nx-3wVMnaWw[youtube, width=640, height=360, align=center]

.1999-2000 Vermilion Sailor Marching Band - Pregame - Alma Mater
video::EUZSSXVxCY8[youtube, width=640, height=360, align=center]

.2004-2005 Vermilion Sailor Marching Band - Alma Mater - Homecoming Ceremony
video::7XxZ4H8XnL4[youtube, width=640, height=360, align=center]

.2007 Vermilion Sailor Alumni Band - Alma Mater
video::g2yvf-CvQSA[youtube, width=640, height=360, align=center]

.2008 Vermilion Sailor Alumni Band - Alma Mater
video::iKVU6yKDx8M[youtube, width=640, height=360, align=center]

.2009 Vermilion Sailor Alumni Band - Alma Mater
video::q7s3B_zcQkw[youtube, width=640, height=360, align=center]

.2010 Vermilion Sailor Alumni Band - Alma Mater
video::q-ht1ZaCNI4[youtube, width=640, height=360, align=center]

.2011 Vermilion Sailor Alumni Band - Alma Mater
video::a94r_ZuV6bw[youtube, width=640, height=360, align=center]

.2012 Vermilion Sailor Alumni Band - Alma Mater
video::wyl6FOP757c[youtube, width=640, height=360, align=center]

.2013 Vermilion Sailor Alumni Band - Alma Mater
video::Vd1bhJ3jsgk[youtube, width=640, height=360, align=center]

.2014 Vermilion Sailor Alumni Band - Alma Mater
video::wDEpfBnWgos[youtube, width=640, height=360, align=center]

.2016 Vermilion Sailor Alumni Band - Alma Mater
video::m4if7mSFhpg[youtube, width=640, height=360, align=center]

.2018 Vermilion Sailor Alumni Band - Alma Mater
video::RDUQ5sUxS2U[youtube, width=640, height=360, align=center]

.2018-2019 Vermilion Sailor Marching Band - Alma Mater Endzone
video::9PGIpf3wKI0[youtube, width=640, height=360, align=center]

.2023 Vermilion Sailor Alumni Band - Alma Mater
video::DHaKvXLQsD0[youtube, width=640, height=360, align=center]

[.text-center]
link:/songs/[Vermilion Sailor Band Songs]